### ISSUE TITLE
Add a section about learning a new tech stack during a voyage

### ISSUE THREAD

**Issue by misomighty** [Chingu-cohorts/pmrok#11]
**_Issue Description & Expected Outcome:_** 
Learning an entirely new tech stack while under time constraints is intimidating. 
A section should be added that includes knowledge on how to avoid the trap of 'analysis paralysis' - where teams spend too much time reading documentation and/or doing courses and not coding.

**_Symptoms:_**
Team members are not pushing their code to the team repo 
Teams are not completing sprint tasks week after week

**_Steps to Recreate:_** 
A compilation of individual experiences dealing with 'analysis paralysis' 

**_Resolution:_** 
A compilation of individual experiences dealing with overcoming 'analysis paralysis'

**Comment by jdmedlock** [comment]
There seems to be at least two separate, but related cases stemming from 'analysis paralysis'. One, as noted in this request is when a team over analyzes new technology. The second, related case is that of the "shiny new object" syndrome resulting from teams making a technology decision, changing to a new related technology, and so on. The end result being the same where no progress is made towards the project goal.

**Comment by jdmedlock** [comment]
Completed the addition of _Section A5. Dealing with "Analysis Paralysis"_ to the wiki. This includes three specific cases related to "analysis paralysis", along with symptoms and preventative and corrective actions. 

This was a great request on your part! Thanks for suggesting it.
