### ISSUE TITLE
Feedback on Unresponsive Member page

### ISSUE THREAD

**Issue by sfiquet** [Chingu-cohorts/pmrok#14]
I found this page very useful. My suggestions:

- It would be useful to include point 3 (life happens but members need to let their PM know) into the Voyage Roadmap - Act 1 Step 2 Set Goals and Expectations: Be clear from the start that team members must get in touch if they need to exit the project, or if they are struggling. I fear that this valuable piece of information could be missed otherwise. If a PM only reads the Unresponsive Member page when they have a problem, it's already too late.

- While reading the part about pair programming, I found myself wondering "how do you pair program effectively, particularly with the goal of helping someone get better?" Could we link to a guide maybe?

**Comment by jdmedlock** [comment]
Thanks for making these suggestions!

1. The "Life Happens" point is being added to the "Your Obligations" section of the Voyage Wiki and we are also discussing in within the larger context of the Acts to see if there are other places where it should be emphasized (for example, the upcoming AMA sessions).

2. A new section will be added to the Voyage Wiki to specifically discuss what Pair Programming is, what its benefits are, and what needs to happen for a pair programming session to be effective. 

Leaving this issue open until #2 is completed.

**Comment by jdmedlock** [comment]
The Pair Programming discussion and references have been added to the Voyage Wiki instead of the PMRoK, which already has a reference to Pair Programming. This was done since it is felt that this information is equally important to the Team as it is to the PM.
